### ISSUE TITLE
An error occurs stating classiq cannot be found when trying to import it.

### ISSUE THREAD

**Issue by applifun** [unitaryfund/unitaryHACK2024#12]
How to solve the problem where, after successfully installing classiq in a local Ubuntu environment, an error occurs stating classiq cannot be found when trying to import it.

①
!pip show classiq

②
import sys 
print(sys.path)

The reason for the issue is that the path shown in the Location from step ① is not included in the list displayed in step ②. Therefore, write the following:

sys.path.append(‘Path from the Location in step ①’)

In my local environment, this worked well for me. I hope it can be one of the solutions.

**Comment by jordandsullivan** [comment]
Hey there, so it sounds like this may be an issue with your Python environment and not with mitiq or classiq specifically, is that accurate?  If you could also add a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), that would be great. 
Is it possible you used a different installation process than the docs recommend? https://mitiq.readthedocs.io/en/latest/index.html

**Comment by applifun** [comment]
I used Lubuntu as my environment. I created a virtual environment, launched Jupyter Lab within it, and executed !pip install -U classiq in a cell. The installation displayed ‘success’. However, when I tried to execute import classiq, I encountered an error stating that classiq could not be found. After I added the path to the list as described above, the error no longer occurred.

**Comment by jordandsullivan** [comment]
I'm not very familiar with Lubuntu myself, but I know it is an Operating System, rather than an environment (like [conda](https://conda.io/projects/conda/en/latest/user-guide/install/index.html) or [venv](https://docs.python.org/3/library/venv.html). 
I would say that at times pip installing from a jupyter notebook rather than from your terminal can lead to path issues if you haven't specified your environment correctly before launching. 

But as you say, you ran into this issue using Classiq rather than Mitiq, so that would probably be a better place for discussion.
